
---
- name: Change root password on remote servers
  hosts: all
  become: yes
  tasks:
    - name: Generate hashed password
      ansible.builtin.command:
        cmd: "openssl passwd -1 {{ new_root_password }}"
      register: hashed_password

    - name: Change root password
      ansible.builtin.user:
        name: root
        password: "{{ hashed_password.stdout }}"
      when: hashed_password.stdout is defined

    - name: Verify root password change
      ansible.builtin.shell:
        cmd: "echo '{{ new_root_password }}' | su -c 'echo Root password changed successfully' - root"
      register: password_check
      failed_when: "'Root password changed successfully' not in password_check.stdout"

    - name: Print success message
      ansible.builtin.debug:
        msg: "Root password changed successfully on {{ inventory_hostname }}"
      when: password_check.stdout.find('Root password changed successfully') != -1
