---
- name: Copy file to remote servers using SCP
  hosts: remote_servers
  tasks:
    - name: Copy file to remote server
      copy:
        src: /path/to/local/file
        dest: /path/to/remote/destination/
